plugins {
    id 'net.fabricmc.fabric-loom'
}

base { archivesName = 'do-not-render-the-helmet-26.3' }

dependencies {
    minecraft 'com.mojang:minecraft:26.3'
    implementation 'net.fabricmc:fabric-loader:0.19.5'
    implementation 'net.fabricmc.fabric-api:fabric-api:0.161.0+26.3'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand([version: project.version]) {
            escapeBackslash = true
        }
    }
}

tasks.withType(JavaCompile).configureEach { options.release = 25 }
java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    withSourcesJar()
}
